# REGISTRATION_DATA
REGISTRATION_FIRST_NAME = 'Andrew'
REGISTRATION_LAST_NAME = 'Smith'
REGISTRATION_PASSWORD = 'StrongPassword123'
REGISTRATION_COMPANY = 'DDD Records'
REGISTRATION_DATE_OF_BIRTH = '30'
REGISTRATION_MONTH_OF_BIRTH = 'September'
REGISTRATION_YEAR_OF_BIRTH = '1986'


# LOGIN DATA
INVALID_EMAIL = 'invalid.email@gmail.com'
INVALID_PASSWORD = 'invalid123'
VALID_EMAIL = 'email@gmail.com'
VALID_PASSWORD = '123123'
